# **PANDAS LIBRARY IN PYTHON**

* Pandas is a powerful open-source Python library used for data manipulation, analysis, and cleaning.

* It provides easy-to-use data structures like:

      * Series → 1-dimensional labeled data

      * DataFrame → 2-dimensional table (rows & columns)

* Pandas is built on top of NumPy and is widely used in data science, ML, analytics, and data preprocessing.
* Pandas allows us to perform operations such as:



```
Load Data
   ↓
Inspect Data
   ↓
Clean Data
   ↓
Transform Data
   ↓
Analyze Data
   ↓
Prepare Data for ML
```

### Why Pandas?

* Easy to read/write datasets (CSV, Excel, SQL, JSON)

* Fast data manipulation

* Handles missing data

* Label-based indexing

* Built-in statistical operations

* Integration with NumPy, Matplotlib, Scikit-Learn

### Importing Pandas

In [165]:
# If Pandas is not installed:
#pip install pandas

In [166]:
import pandas as pd

pd is the commonly used alias for Pandas.

### Key Data Structures

#### 1. **Series**

* A one-dimensional array with labels (index).

###### Creating a Series

In [167]:
s = pd.Series([10, 20, 30, 40])
print(s)
print()

print(s[0])
print(s[2])

0    10
1    20
2    30
3    40
dtype: int64

10
30

In [168]:
print(s[0:3])

0    10
1    20
2    30
dtype: int64

###### Creating a Series with Custom Index

In [169]:
data = {'Math': 85, 'Science': 90, 'English': 88}
# HERE Math , Science , English are the labels and 85 ,90,88 are the values
s = pd.Series(data)
print(s)

Math       85
Science    90
English    88
dtype: int64

In [170]:
data['English']

88

In [171]:
data['Math']

85

In [172]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [173]:
print(s['a'])
print(s['b'])
print(s['c'])

10
20
30

In [174]:
marks = pd.Series(
    [80, 90, 75],
    index=["Alice", "Bob", "Rahul"]
)

print(marks)

Alice    80
Bob      90
Rahul    75
dtype: int64

In [175]:
print(marks["Alice"])

80

In [176]:
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

print(a + b)
print(a * 2)
print(a.mean())
print(a.max())

0    5
1    7
2    9
dtype: int64
0    2
1    4
2    6
dtype: int64
2.0
3

#### 2. **DataFrame**

* A table-like structure with rows and columns.

From Dictionary:

In [177]:
df = pd.DataFrame({
    "Name": ["Achu", "Rahul", "John","Alex","Ramya","Ananthu","Arya"],
    "Study_hour":[4,3,4,1,2,5,4],
    "Marks": [90, 85, 88,50,60,98,91]
})

In [178]:
df

      Name  Study_hour  Marks
0     Achu           4     90
1    Rahul           3     85
2     John           4     88
3     Alex           1     50
4    Ramya           2     60
5  Ananthu           5     98
6     Arya           4     91

From List of Lists:

In [179]:
data = [
    ['Achu', 22, 85],
    ['John', 25, 90],
    ['Meera', 23, 88]
]

df = pd.DataFrame(data, columns=['Name', 'Age', 'Marks'])
print(df)

    Name  Age  Marks
0   Achu   22     85
1   John   25     90
2  Meera   23     88

In [180]:
df['Name']

0     Achu
1     John
2    Meera
Name: Name, dtype: object

In [181]:
df['Marks']

0    85
1    90
2    88
Name: Marks, dtype: int64

In [182]:
df['Marks'][0]                    # PRINTS THE MARK OF FIRST STUDENT

np.int64(85)

In [183]:
df['Name'][0]                     # PRINTS THE NAME OF FIRST STUDENT

'Achu'

In [184]:
df[['Name','Marks']]               # SELECTING PARTICULAR COLUMNS FROM THE DATAFRAME

    Name  Marks
0   Achu     85
1   John     90
2  Meera     88

In [185]:
df[df['Marks']>87]                 # SELECTING THE ROWS WHERE MARKS GREATER THAN 87

    Name  Age  Marks
1   John   25     90
2  Meera   23     88

##### loc vs iloc

In [186]:
# Creating a DataFrame
data = {
    "Name": ["Anu", "Rahul", "Meera", "Arjun"],
    "Age": [20, 21, 19, 22],
    "Course": ["Data Science", "Python", "Data Science", "AI"]
}

df = pd.DataFrame(data, index=["S1", "S2", "S3", "S4"])
df

     Name  Age        Course
S1    Anu   20  Data Science
S2  Rahul   21        Python
S3  Meera   19  Data Science
S4  Arjun   22            AI

In [187]:
# Select row with label S2
print(df.loc["S2"])

Name       Rahul
Age           21
Course    Python
Name: S2, dtype: object

In [188]:
print(df.loc[["S1", "S3"]])

     Name  Age        Course
S1    Anu   20  Data Science
S3  Meera   19  Data Science

In [189]:
print(df.loc["S3", "Course"])

Data Science

In [190]:
# Select the second row
print(df.iloc[1])

Name       Rahul
Age           21
Course    Python
Name: S2, dtype: object

In [191]:
print(df.iloc[[0, 2]])

     Name  Age        Course
S1    Anu   20  Data Science
S3  Meera   19  Data Science

In [192]:
df = pd.DataFrame({
    "Name": ["Achu", "Rahul", "John","Alex","Ramya","Ananthu","Arya"],
    "Study_hour":[4,3,4,1,2,5,4],
    "Marks": [90, 85, 88,50,60,98,91]
})

loc is label-based selection.

In [193]:
print(df.loc[0])          # selects the row with index 0.

Name          Achu
Study_hour       4
Marks           90
Name: 0, dtype: object

In [194]:
df.loc[0:2]                  # PRINTS THE ROWS FROM 0 TO 2(INCLUDED) USING LABELS

    Name  Study_hour  Marks
0   Achu           4     90
1  Rahul           3     85
2   John           4     88

iloc is integer-position based selection.

In [195]:
print(df.iloc[0])       #First row.

Name          Achu
Study_hour       4
Marks           90
Name: 0, dtype: object

In [196]:
df.iloc[0:3]                 # First 3 rows.

    Name  Study_hour  Marks
0   Achu           4     90
1  Rahul           3     85
2   John           4     88

In [197]:
print(df.iloc[0:3, 0:2])   # First three rows and first two columns.

    Name  Study_hour
0   Achu           4
1  Rahul           3
2   John           4

#### Filtering Data

In [198]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Rahul", "Anu", "John"],
    "Age": [20, 21, 20, 22, 21],
    "Course": [
        "Data Science",
        "Python",
        "Data Science",
        "Python",
        "Data Science"
    ],
    "Marks": [85, 78, 92, 88, 76],
    "Attendance": [90, 85, 95, 88, 80]
}

df = pd.DataFrame(data)

print(df)

    Name  Age        Course  Marks  Attendance
0  Alice   20  Data Science     85          90
1    Bob   21        Python     78          85
2  Rahul   20  Data Science     92          95
3    Anu   22        Python     88          88
4   John   21  Data Science     76          80

In [199]:
# students with marks greater than 80.

high_marks = df[df["Marks"] > 80]

print(high_marks)

    Name  Age        Course  Marks  Attendance
0  Alice   20  Data Science     85          90
2  Rahul   20  Data Science     92          95
3    Anu   22        Python     88          88

In [200]:
# Students with marks greater than 80 and attendance greater than 90:
result = df[
    (df["Marks"] > 80) &
    (df["Attendance"] > 90)
]

print(result)

    Name  Age        Course  Marks  Attendance
2  Rahul   20  Data Science     92          95

In [201]:
result = df[
    (df["Marks"] > 90) |
    (df["Attendance"] > 90)
]

print(result)

    Name  Age        Course  Marks  Attendance
2  Rahul   20  Data Science     92          95

Adding a New Column

In [202]:
df["Result"] = "Pass"
print(df)

    Name  Age        Course  Marks  Attendance Result
0  Alice   20  Data Science     85          90   Pass
1    Bob   21        Python     78          85   Pass
2  Rahul   20  Data Science     92          95   Pass
3    Anu   22        Python     88          88   Pass
4   John   21  Data Science     76          80   Pass

In [203]:
df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)
df

    Name  Age        Course  Marks  Attendance Result
0  Alice   20  Data Science     85          90   Pass
1    Bob   21        Python     78          85   Pass
2  Rahul   20  Data Science     92          95   Pass
3    Anu   22        Python     88          88   Pass
4   John   21  Data Science     76          80   Pass

Updating a Column

In [204]:
df["Marks"] = df["Marks"] + 5

Removing a Column

In [205]:
df = df.drop("Attendance", axis=1)

axis=0 → rows

axis=1 → columns

In [206]:
# Removing Rows
df = df.drop(0)

In [207]:
# Sorting Data
df = df.sort_values("Marks")
df

    Name  Age        Course  Marks Result
4   John   21  Data Science     81   Pass
1    Bob   21        Python     83   Pass
3    Anu   22        Python     93   Pass
2  Rahul   20  Data Science     97   Pass

In [208]:
df = df.sort_values(
    "Marks",
    ascending=False
)
df

    Name  Age        Course  Marks Result
2  Rahul   20  Data Science     97   Pass
3    Anu   22        Python     93   Pass
1    Bob   21        Python     83   Pass
4   John   21  Data Science     81   Pass

In [209]:
print(df["Marks"].max())
print(df["Marks"].min())
print(df["Marks"].mean())
print(df["Marks"].median())
print(df["Marks"].sum())

97
81
88.5
88.0
354

In [210]:
print(df["Course"].unique())

['Data Science' 'Python']

In [211]:
print(df["Course"].nunique())

2

In [212]:
print(df["Course"].value_counts())

Course
Data Science    2
Python          2
Name: count, dtype: int64

# Reading Files using Pandas

In [237]:
df= pd.read_csv("/content/tips.csv")
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [238]:
df.head()               # DISPLAYS THE FIRST 5 ROWS

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [239]:
df.head(10)

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4
5           5       25.29  4.71    Male     No  Sun  Dinner     4
6           6        8.77  2.00    Male     No  Sun  Dinner     2
7           7       26.88  3.12    Male     No  Sun  Dinner     4
8           8       15.04  1.96    Male     No  Sun  Dinner     2
9           9       14.78  3.23    Male     No  Sun  Dinner     2

In [240]:
df.tail()                 # DISPLAYS THE LAST 5 ROWS

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

In [241]:
df.sample()

     Unnamed: 0  total_bill  tip   sex smoker   day   time  size
130         130       19.08  1.5  Male     No  Thur  Lunch     2

In [242]:
df.info()                      # DISPLAYS THE INFORMATION LIKE COLUMN NAME,NON-NULL COUNT , DATATYPE OF EACH COLUMN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         244 non-null    float64
 3   sex         244 non-null    object
 4   smoker      244 non-null    object
 5   day         244 non-null    object
 6   time        244 non-null    object
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.4+ KB

In [243]:
df.shape

(244, 8)

In [244]:
df.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='object')

In [245]:
df.dtypes

Unnamed: 0      int64
total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [246]:
df.describe()     # Returns key statistical measures for numerical columns by default

       Unnamed: 0  total_bill         tip        size
count  244.000000  244.000000  244.000000  244.000000
mean   121.500000   19.785943    2.998279    2.569672
std     70.580923    8.902412    1.383638    0.951100
min      0.000000    3.070000    1.000000    1.000000
25%     60.750000   13.347500    2.000000    2.000000
50%    121.500000   17.795000    2.900000    2.000000
75%    182.250000   24.127500    3.562500    3.000000
max    243.000000   50.810000   10.000000    6.000000

In [247]:
df.describe(include='O')   # RETURNS OBJECT COLUMN'S COUNT,NO.OF UNIQUE VALUES, TOP VALUE AND FREQUENCY OF TOP VALUE

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [248]:
df.describe(include='all')    # To include non-numerical columns

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size
count,244.000000,244.000000,244.000000,244,244,244,244,244.000000
unique,NaN,NaN,NaN,2,2,4,2,NaN
top,NaN,NaN,NaN,Male,No,Sat,Dinner,NaN
freq,NaN,NaN,NaN,157,151,87,176,NaN
mean,121.500000,19.785943,2.998279,NaN,NaN,NaN,NaN,2.569672
std,70.580923,8.902412,1.383638,NaN,NaN,NaN,NaN,0.951100
min,0.000000,3.070000,1.000000,NaN,NaN,NaN,NaN,1.000000
25%,60.750000,13.347500,2.000000,NaN,NaN,NaN,NaN,2.000000
50%,121.500000,17.795000,2.900000,NaN,NaN,NaN,NaN,2.000000
75%,182.250000,24.127500,3.562500,NaN,NaN,NaN,NaN,3.000000
max,243.000000,50.810000,10.000000,NaN,NaN,NaN,NaN,6.000000

In [249]:
df[['total_bill','tip']].describe()    # RETURNS DESCRIPTION OF PARTICULAR COLUMNS

       total_bill         tip
count  244.000000  244.000000
mean    19.785943    2.998279
std      8.902412    1.383638
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.900000
75%     24.127500    3.562500
max     50.810000   10.000000

In [250]:
df['total_bill'].describe()           # DESCRIPTION OF A PARTICULAR COLUMN

count    244.000000
mean      19.785943
std        8.902412
min        3.070000
25%       13.347500
50%       17.795000
75%       24.127500
max       50.810000
Name: total_bill, dtype: float64

Creating a new column

In [251]:
df["Customer"] = df['total_bill'].apply(
    lambda x: "Premium Customer" if x >= 18 else "Normal")
df

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size,Customer
0,0,16.99,1.01,Female,No,Sun,Dinner,2,Normal
1,1,10.34,1.66,Male,No,Sun,Dinner,3,Normal
2,2,21.01,3.50,Male,No,Sun,Dinner,3,Premium Customer
3,3,23.68,3.31,Male,No,Sun,Dinner,2,Premium Customer
4,4,24.59,3.61,Female,No,Sun,Dinner,4,Premium Customer
...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,Premium Customer
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,Premium Customer
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,Premium Customer
242,242,17.82,1.75,Male,No,Sat,Dinner,2,Normal
243,243,18.78,3.00,Female,No,Thur,Dinner,2,Premium Customer

Removing a Column

In [252]:
df = df.drop("Unnamed: 0", axis=1)

axis=0 → rows

axis=1 → columns

In [253]:
# Removing Rows
df = df.drop(0)

In [254]:
# Sorting Data
df = df.sort_values("tip")
df

     total_bill    tip     sex smoker   day    time  size          Customer
92         5.75   1.00  Female    Yes   Fri  Dinner     2            Normal
111        7.25   1.00  Female     No   Sat  Dinner     1            Normal
67         3.07   1.00  Female    Yes   Sat  Dinner     1            Normal
236       12.60   1.00    Male    Yes   Sat  Dinner     2            Normal
215       12.90   1.10  Female    Yes   Sat  Dinner     2            Normal
..          ...    ...     ...    ...   ...     ...   ...               ...
141       34.30   6.70    Male     No  Thur   Lunch     6  Premium Customer
59        48.27   6.73    Male     No   Sat  Dinner     4  Premium Customer
23        39.42   7.58    Male     No   Sat  Dinner     4  Premium Customer
212       48.33   9.00    Male     No   Sat  Dinner     4  Premium Customer
170       50.81  10.00    Male    Yes   Sat  Dinner     3  Premium Customer

[243 rows x 8 columns]

In [255]:
df = df.sort_values(
    "tip",
    ascending=False
)
df

     total_bill    tip     sex smoker   day    time  size          Customer
170       50.81  10.00    Male    Yes   Sat  Dinner     3  Premium Customer
212       48.33   9.00    Male     No   Sat  Dinner     4  Premium Customer
23        39.42   7.58    Male     No   Sat  Dinner     4  Premium Customer
59        48.27   6.73    Male     No   Sat  Dinner     4  Premium Customer
141       34.30   6.70    Male     No  Thur   Lunch     6  Premium Customer
..          ...    ...     ...    ...   ...     ...   ...               ...
215       12.90   1.10  Female    Yes   Sat  Dinner     2            Normal
236       12.60   1.00    Male    Yes   Sat  Dinner     2            Normal
92         5.75   1.00  Female    Yes   Fri  Dinner     2            Normal
111        7.25   1.00  Female     No   Sat  Dinner     1            Normal
67         3.07   1.00  Female    Yes   Sat  Dinner     1            Normal

[243 rows x 8 columns]

### Data Cleaning & Manipulation with Pandas

* Data cleaning involves preparing raw data by correcting or removing incorrect, incomplete, or irrelevant data.

#### 1. Handling Missing Values

In [256]:
data = {
    'Name': ['Achu', 'John', 'Meera', 'Ravi'],
    'Age': [22, None, 23, None],
    'Marks': [85, 90, None, 70]
}

df = pd.DataFrame(data)
print(df)

    Name   Age  Marks
0   Achu  22.0   85.0
1   John   NaN   90.0
2  Meera  23.0    NaN
3   Ravi   NaN   70.0

In [257]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     2 non-null      float64
 2   Marks   3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes

Check Missing Values

In [258]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

In [259]:
df.isnull().sum()

Name     0
Age      2
Marks    1
dtype: int64

In [260]:
df.isnull().sum().sum()

np.int64(3)

In [261]:
df.isna()          # True for missing values
df.isna().sum()    # Count missing values column-wise

Name     0
Age      2
Marks    1
dtype: int64

In [262]:
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

dropna() – Remove missing values

In [263]:
df_drop = df.dropna()     # Remove rows with any NaN:
df_drop

   Name   Age  Marks
0  Achu  22.0   85.0

In [264]:
df_drop_col = df.dropna(axis=1)  # Remove columns with NaN:

In [265]:
df_drop_col

    Name
0   Achu
1   John
2  Meera
3   Ravi

fillna() – Replace missing values

In [266]:
df_filled = df.fillna(0)       # Fill with specific value:

In [267]:
df_filled

    Name   Age  Marks
0   Achu  22.0   85.0
1   John   0.0   90.0
2  Meera  23.0    0.0
3   Ravi   0.0   70.0

In [268]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [269]:
df

    Name   Age      Marks
0   Achu  22.0  85.000000
1   John  22.5  90.000000
2  Meera  23.0  81.666667
3   Ravi  22.5  70.000000

In [270]:
print(df.duplicated())

0    False
1    False
2    False
3    False
dtype: bool

In [271]:
print(df.duplicated())

0    False
1    False
2    False
3    False
dtype: bool

In [272]:
df = df.rename(
    columns={"Marks": "Score"}
)
df

    Name   Age      Score
0   Achu  22.0  85.000000
1   John  22.5  90.000000
2  Meera  23.0  81.666667
3   Ravi  22.5  70.000000

In [273]:
df["Age"] = df["Age"].astype(int)

In [274]:
df["Age"] = df["Age"].astype(int)

In [275]:
df.dtypes

Name      object
Age        int64
Score    float64
dtype: object

## Writing DataFrame to CSV

In [276]:
df.to_csv("output.csv", index=False)

Writing to Excel

In [277]:
df.to_excel("output.xlsx", index=False)

## GroupBy

In [278]:
df

    Name  Age      Score
0   Achu   22  85.000000
1   John   22  90.000000
2  Meera   23  81.666667
3   Ravi   22  70.000000

In [279]:
# the average marks for each course.
result = df.groupby("Age")["Score"].mean()
print(result)

Age
22    81.666667
23    81.666667
Name: Score, dtype: float64

In [280]:
result = df.groupby("Age")["Score"].agg(
    ["mean", "max", "min", "count"]
)
print(result)

          mean        max        min  count
Age
22   81.666667  90.000000  70.000000      3
23   81.666667  81.666667  81.666667      1

In [281]:
def grade(marks):

    if marks >= 90:
        return "A"

    elif marks >= 80:
        return "B"

    elif marks >= 70:
        return "C"

    else:
        return "D"


df["Grade"] = df["Score"].apply(grade)

print(df)

    Name  Age      Score Grade
0   Achu   22  85.000000     B
1   John   22  90.000000     A
2  Meera   23  81.666667     B
3   Ravi   22  70.000000     C

## Combining DataFrames — concat()

In [282]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Marks": [85, 78]
})

df2 = pd.DataFrame({
    "Name": ["Rahul", "Anu"],
    "Marks": [92, 88]
})

result = pd.concat([df1, df2])
print(result)

    Name  Marks
0  Alice     85
1    Bob     78
0  Rahul     92
1    Anu     88

In [283]:
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Rahul"]
})

marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 78, 92]
})

result = pd.merge(
    students,
    marks,
    on="ID"
)

print(result)

   ID   Name  Marks
0   1  Alice     85
1   2    Bob     78
2   3  Rahul     92

| Task                     | Pandas Code                   |
| ------------------------ | ----------------------------- |
| Import Pandas            | `import pandas as pd`         |
| Create DataFrame         | `pd.DataFrame()`              |
| Read CSV                 | `pd.read_csv()`               |
| Read Excel               | `pd.read_excel()`             |
| First rows               | `df.head()`                   |
| Last rows                | `df.tail()`                   |
| Rows & columns           | `df.shape`                    |
| Column names             | `df.columns`                  |
| Data types               | `df.dtypes`                   |
| Dataset information      | `df.info()`                   |
| Statistics               | `df.describe()`               |
| Select column            | `df["column"]`                |
| Select rows              | `df.loc[]`                    |
| Position-based selection | `df.iloc[]`                   |
| Filter                   | `df[df["column"] > value]`    |
| Missing values           | `df.isnull()`                 |
| Remove missing           | `df.dropna()`                 |
| Fill missing             | `df.fillna()`                 |
| Remove duplicates        | `df.drop_duplicates()`        |
| Sort                     | `df.sort_values()`            |
| Group data               | `df.groupby()`                |
| Unique values            | `df["column"].unique()`       |
| Frequency                | `df["column"].value_counts()` |
| Add column               | `df["new"] = ...`             |
| Remove column            | `df.drop()`                   |
| Rename                   | `df.rename()`                 |
| Combine                  | `pd.concat()`                 |
| Merge                    | `pd.merge()`                  |
| Save CSV                 | `df.to_csv()`                 |